version: '3'
services:
    web_:
        container_name: krpl_web
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./../:/var/www:Z
            - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
        networks:
            - krpl
        links:
            - redis:redis
            - mongo:mongo

    php:
        container_name: krpl_php
        build:
            context: './php'
        restart: always
        volumes:
            - ./../:/var/www:Z
        working_dir: /var/www
        networks:
             - krpl

    db:
        container_name: krpl_db
        image: mysql:5.7
#        command: --default-autexitentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "1111"
            MYSQL_ROOT_PASSWORD: "1111"
            MYSQL_DATABASE: "kryptowaluty_pl"
        volumes:
            - ../var/docker/mysql:/var/lib/mysql:Z
        networks:
            - krpl

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: "1111"
        networks:
            - krpl

    mongo:
        container_name: krpl_mongo
        image: mongo:latest
        restart: always
        volumes:
            - ../var/docker/mongodb:/data/db:Z
        ports:
            - 27017:27017
        networks:
            - krpl

    redis:
        container_name: krpl_redis
        image: library/redis:alpine
        restart: always
        ports:
            - 6379:6379
        networks:
            - krpl

networks:
    krpl:
